### ISSUE TITLE
Grußtext

### ISSUE THREAD

**Issue by droscha** [Nordisk-Buero/Seasons-Greetings-2017#17]
So lautet der aktuell abgestimmte Gruß – inhaltl. und Schreibweise?
Merry Christmas With Love And Happiness!
Nicht mehr Season’s Greeting?

**Comment by JonathanSchndr** [comment]
yes

**Comment by tmaier-nordisk** [comment]
anscheinend heißt die "seasons greetings card" jetzt auch "Christmas card" ;-)
