### ISSUE TITLE
Workflow SCSS/SASS/CSS

### ISSUE THREAD

**Issue by tmaier-nordisk** [Nordisk-Buero/Seasons-Greetings-2017#8]
mit PrePros (im PrePros Config) oder Terminal:

zwei Workflows:
 * SCSS schreiben
** -> kompiliert und ersetzt SASS
** -> kompiliert und ersetzt minifiziertes CSS

* SASS schreiben
** -> kompiliert und ersetzt SCSS
** -> kompiliert und ersetzt minifiziertes CSS

**Comment by JonathanSchndr** [comment]
Aktuell bitte SCSS > CSS benutzen. Workflow nochmals separat besprechen.
